server:
  servlet:
    context-path: /bank-account

spring:
  datasource:
    url: jdbc:h2:mem:bank
    username: amine
    password: amine
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
